import Head from "next/head";
import Link from "next/link";
import { GetStaticProps } from "next";
import { useTranslation, Trans } from "next-i18next";
import { serverSideTranslations } from "next-i18next/serverSideTranslations";

import desk_top from '../../public/desk_top.jpg'
import Navbar from "./components/Navbar";

export default function LandingPage() {
  const { t, i18n } = useTranslation("common");
  const header = (
    <header
      className="flex items-center justify-center h-screen mb-12 bg-fixed bg-center bg-cover custom-img"
      style={{
        backgroundImage: `url(${desk_top.src})`,
      }}
    >
      <Navbar key={"navbar"}></Navbar>
      <div className="p-4 text-white bg-transparent  rounded-xl">
        <p className="text-4xl text-center">nice to e-meet you.</p>
      </div>
      <div className="p-6 text-white bg-purple-600 bg-opacity-50 rounded-xl">
        <p className="text-6xl text-center">
          the name, <strong>abdul rahim</strong>
        </p>
      </div>
    </header>
  );

  const secondSection = (
    <div className="max-w-lg m-auto">
      <p className="mb-4">
        {t("description")}
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec placerat
        a magna non varius. Proin leo felis, euismod non porta eget, varius sit
        amet sapien. Maecenas in nulla at leo convallis consectetur id a sapien.
        Nulla nec pulvinar nisi. Vivamus non facilisis lacus, et volutpat
        libero. Nulla ac odio aliquam, accumsan arcu ut, lacinia est. Nulla eu
        sem elit. Fusce nec laoreet sem, semper molestie libero.
      </p>
      <p className="mb-12">
        Nulla pharetra lacinia nisi, vitae mollis tellus euismod id. Mauris
        porta dignissim hendrerit. Cras id velit varius, fermentum lectus vitae,
        ultricies dolor. In bibendum rhoncus purus vel rutrum. Nam vulputate
        imperdiet fringilla. Donec blandit libero massa. Suspendisse dictum diam
        mauris, vitae fermentum dolor tincidunt in. Pellentesque sollicitudin
        venenatis dolor, vitae scelerisque elit ultrices eu. Donec eget sodales
        risus, quis dignissim neque.
      </p>
    </div>
  );

  const thirdSection = (
    <section
      className="container flex items-center justify-center h-screen m-auto mb-12 bg-fixed bg-center bg-cover custom-img"
      style={{
        backgroundImage:
          'url("https://images.unsplash.com/photo-1454496522488-7a8e488e8606?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=1955&q=80")',
      }}
    >
      <div className="p-5 text-2xl text-white bg-purple-300 bg-opacity-50 rounded-xl">
        Parallax inline
      </div>
    </section>
  );

  const fourthSection = (
    <div className="max-w-lg m-auto">
      <p className="mb-4">
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec placerat
        a magna non varius. Proin leo felis, euismod non porta eget, varius sit
        amet sapien. Maecenas in nulla at leo convallis consectetur id a sapien.
        Nulla nec pulvinar nisi. Vivamus non facilisis lacus, et volutpat
        libero. Nulla ac odio aliquam, accumsan arcu ut, lacinia est. Nulla eu
        sem elit. Fusce nec laoreet sem, semper molestie libero.
      </p>
      <p className="mb-4">
        Ut sagittis lacus consequat accumsan venenatis. Sed sollicitudin, lectus
        et fringilla ultrices, dolor nisi scelerisque tortor, vel finibus magna
        massa non nunc. Phasellus massa quam, egestas a nisl sed, porta volutpat
        metus. Nunc sed elit ac tellus tempor cursus. Suspendisse potenti.
        Vestibulum varius rutrum nisl nec consequat. Suspendisse semper
        dignissim sem viverra semper. Nulla porttitor, purus nec accumsan
        pharetra, nisi dolor condimentum ipsum, id consequat nulla nunc in
        ligula.
      </p>
    </div>
  );

  return (
    <>
      <Head>
        <title>NextJS/ReactJS Template</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {header}

      {secondSection}

      {thirdSection}

      {fourthSection}
    </>
  );
}

export const getStaticProps: GetStaticProps<{}> = async ({ locale }) => ({
  props: {
    ...(await serverSideTranslations(locale ?? "en", ["common"])),
  },
});
